version: '2'

services:
  backend:
    restart: always
    image: node:20-bullseye-slim
    entrypoint: /bin/bash
    command: -c "yarn install && yarn dev"
    container_name: backend
    working_dir: "/backend"
    volumes:
      - ./backend:/backend
    tty: true

  webserver:
    container_name: "webserver"
    image: nginx:latest
    volumes_from:
      - backend:r
    ports:
      - '80:80'
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/_services:/etc/nginx/conf.d/_services
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongodb:/data/db

  mongo-express:
    container_name: mongodb-gui
    image: mongo-express:latest
    restart: unless-stopped
    depends_on: 
      - mongodb 
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=user100